### ISSUE TITLE
Error after Atom update to 1.3.3

### ISSUE THREAD

**Issue by Grohotun** [ericfreese/font-viewer#10]
index.js:62 
/Users/grohotun/.atom/packages/font-viewer/lib/font-viewer-view.coffee:15:5: error: cannot call super outside of an instance method.
    super
    ^^^^^handleSetupError @ index.js:62

**Comment by nmccready** [comment]
This line looks like a typo https://github.com/ericfreese/font-viewer/blob/master/lib/font-viewer-view.coffee#L13

**Comment by ericfreese** [comment]
Yeah, definitely a typo. Should probably just be reverted. I'll fix it when I have some time, but a PR would be appreciated!

**Comment by ghpabs** [comment]
Since installing font-viewer I can't launch Atom anymore.

I'm getting the same error described above.

Is there a clean way to uninstall this package?

**Comment by aminya** [comment]
This is already fixed
