### ISSUE TITLE
Hangs Atom completely

### ISSUE THREAD

**Issue by gregthebusker** [ericfreese/font-viewer#12]
I installed this today with Atom version 1.7.2 and I could no longer open up any files.  After trying to restart atom I just got a blank white screen.  Needed to uninstall this packages with apm in order to recover.

**Comment by ggallo** [comment]
+1

**Comment by matochondrion** [comment]
with atom 1.14.3

**Comment by aminya** [comment]
This is fixed in version 0.4 and above.
