### ISSUE TITLE
It wouldn't install

### ISSUE THREAD

**Issue by ajmeese7** [ericfreese/font-viewer#14]
This is the error message:

**Installing “font-viewer@0.3.1” failed.

> freetype2@0.3.0 install C:\Users\DECLAR~1\AppData\Local\Temp\apm-install-dir-116510-62012-h2ujh4\node_modules\font-viewer\node_modules\freetype2
> node-gyp rebuild

C:\Users\DECLAR~1\AppData\Local\Temp\apm-install-dir-116510-62012-h2ujh4\node_modules\font-viewer\node_modules\freetype2>if not defined npm_config_node_gyp (node "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\DeclaredDig10\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\DeclaredDig10\.atom\.apm\.apmrc" "--userconfig" "C:\Users\DeclaredDig10\.atom\.apmrc" "install" "C:\Users\DECLAR~1\AppData\Local\Temp\d-116510-62012-szbc04\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.**

**Comment by marcus13345** [comment]
+1, same issue here

**Comment by jakub-g** [comment]
seems it could be due to `apm` bundling a very ancient version of node

https://github.com/atom/apm/issues/328
