### ISSUE TITLE
Can't view a TTF font

### ISSUE THREAD

**Issue by foucdeg** [ericfreese/font-viewer#16]
When opening any TTF font file, Atom won't switch to the tab and won't close it either.

Every time I click on the tab or its close button, I get 
```
Uncaught (in promise) SyntaxError: cannot call super outside of an instance method
```
in the Electron/Chrome inspector.

**Comment by alflanagan** [comment]
Looks to me like commit a351726c6163c9c0ed78065a035c34600c4dcee6 left the word 'preview' hanging out all by itself on line 13 of lib/font-viewer-view.coffee. But when I removed it, it crashed atom (beta 1.13). So I don't know...

**Comment by aminya** [comment]
The package now is able to view ttf fonts.
