### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by ericfreese** [ericfreese/font-viewer#18]
Hi all. Apologies this package has been neglected for so long. I no longer use Atom so it's hard for me to find the time to maintain this package. Would someone here be willing to take over maintenance of it? I can add you as a collaborator to the repo so that you can merge pull requests and handle publishing new versions.

**Comment by aminya** [comment]
@ericfreese I can help to maintain this package. I made a pull request that revives the package.
https://github.com/ericfreese/font-viewer/pull/23

**Comment by ericfreese** [comment]
Great! Sent you an invite :+1:

**Comment by aminya** [comment]
Thank you! 🎉
