### ISSUE TITLE
Installing “font-viewer@0.3.0” failed (tried 3x)

### ISSUE THREAD

**Issue by Anandajoti** [ericfreese/font-viewer#8]
Installing “font-viewer@0.3.0” failed.Hide output…

> freetype2@0.2.3 install D:\TEMP\TMP\apm-install-dir-1151027-3976-hfpapg\node_modules\font-viewer\node_modules\freetype2
> node-gyp rebuild

D:\TEMP\TMP\apm-install-dir-1151027-3976-hfpapg\node_modules\font-viewer\node_modules\freetype2>if not defined npm_config_node_gyp (node "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\bin\node.exe" "C:\Users\Anandajoti\AppData\Local\atom\app-1.3.0-beta6\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Anandajoti\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Anandajoti\.atom\.apmrc" "install" "D:\TEMP\TMP\d-1151027-3976-jo7q8n\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

**Comment by ericfreese** [comment]
There was a problem with the plugin specifying an old version of freetype2.

Should be fixed with version 0.3.1.

**Comment by Anandajoti** [comment]
Hi Eric, just tried to install again, this is the error output:
Installing “font-viewer@0.3.1” failed.Hide output…

> freetype2@0.3.0 install D:\TEMP\TMP\apm-install-dir-1151119-5388-1gesqg0\node_modules\font-viewer\node_modules\freetype2
> node-gyp rebuild


D:\TEMP\TMP\apm-install-dir-1151119-5388-1gesqg0\node_modules\font-viewer\node_modules\freetype2>if not defined npm_config_node_gyp (node "C:\Users\Anandajoti\AppData\Local\atom\app-1.4.0-beta2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Anandajoti\\AppData\\Local\\atom\\app-1.4.0-beta2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Anandajoti\\AppData\\Local\\atom\\app-1.4.0-beta2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Anandajoti\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Anandajoti\\.atom\\.apmrc" "install" "D:\\TEMP\\TMP\\d-1151119-5388-pf1c59\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

**Comment by ericfreese** [comment]
Huh... I'm not very familiar with Node + Windows, but it looks like freetype2 isn't compiling correctly. It's a native addon and uses the [node-gyp](https://github.com/nodejs/node-gyp) module to manage compilation on different platforms.

You might check out node-gyp's [installation notes for Windows](https://github.com/nodejs/node-gyp#installation) and make sure you have all the dependencies. [This](https://github.com/nodejs/node-gyp/issues/629) might also be relevant, though I honestly didn't read through it all.

In the past, have you been able to compile other native addons using node-gyp?

**Comment by Anandajoti** [comment]
Hi Eric, thanks for the reply, I am unsure if any of the addons were compiled with node-gyp, as it all happens in the background until something goes wrong, as here. Looking at node's installation notes however it would seem to me that you have to install so much just to be able to get node-gyp top worj it is hardly worth it. Like all of this applies:

        Windows 10:
            Install the latest version of npm (3.3.6 at the time of writing)
            Install Python 2.7 from https://www.python.org/download/releases/2.7/ and make sure its on the System Path
            Install Visual Studio Community 2015 Edition. (Custom Install, Select Visual C++ during the installation)
            Set the environment variable GYP_MSVS_VERSION=2015
            Run the command prompt as Administrator
            $ npm install (--msvs_version=2015) <-- Shouldn't be needed if you have set GYP_MSVS_VERSION env
            If the above steps have not worked or you are unsure please visit http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64 for a full walkthrough
        All Windows Versions
            For 64-bit builds of node and native modules you will also need the Windows 7 64-bit SDK
            You may need to run one of the following commands if your build complains about WindowsSDKDir not being set, and you are sure you have already installed the SDK:

call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x86
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x64
